MakeMeMove/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('webpages.urls')),
    path('homes/', include('homes.urls')),
    path('renters/', include('renters.urls')),
    path('contacts/', include('contacts.urls')),
    path('userprofiles/', include('userprofiles.urls')),
    path('agents', include('agents.urls')),
    path('advertising', include('advertising.urls')),
    path('admin/', admin.site.urls),
    
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

homes/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.homeList, name='homes'),
    path('<int:home_id>', views.home, name='home'),
    path('lookup', views.lookup, name='lookup'),
    path('seller', views.seller, name='seller')

]

homes/models.py
from django.db import models
from agents.models import Agent
from django.contrib.auth.models import User
from datetime import datetime


# Create your models here.

class Home(models.Model):
    """Creating the components of Listing; to be coupled with the movingdb database."""
    agent = models.ForeignKey(Agent, on_delete=models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, related_name=None)
    property_title = models.CharField(max_length=150)
    address = models.CharField(max_length=150)
    city = models.CharField(max_length=200)
    State_Choices = (
        ("AL", "AL"), ("AK", "AK"), ("AZ", "AZ"), ("AR", "AR"), ("CA", "CA"),
        ("CO", "CO"), ("CT", "CT"), ("DE", "DE"), ("FL", "FL"), ("GA", "GA"),
        ("HI", "HI"), ("ID", "ID"), ("IL", "IL"), ("IN", "IN"), ("IA", "IA"), ("KS", "KS"),
        ("KY", "KY"), ("LA", "LA"), ("ME", "ME"), ("MD", "MD"), ("MA", "MA"),
        ("MI", "MI"), ("MN", "MN"), ("MS", "MS"), ("MO", "MO"), ("MT", "MT"),
        ("NE", "NE"), ("NV", "NV"), ("NH", "NH"), ("NJ", "NJ"), ("NM", "NM"),
        ("NY", "NY"), ("NC", "NC"), ("ND", "ND"), ("OH", "OH"), ("OK", "OK"),
        ("OR", "OR"), ("PA", "PA"), ("RI", "RI"), ("SC", "SC"),
        ("SD", "SD"), ("TN", "TN"), ("TX", "TX"), ("UT", "UT"), ("VT", "VT"), ("VA", "VA"),
        ("WA", "WA"), ("WV", "WV"), ("WI", "WI"), ("WY", "WY"),

    ) 
    state = models.CharField(max_length=100, choices= State_Choices)
    zipcode = models.CharField(max_length=100)
    information = models.TextField(default='')
    price = models.IntegerField()
    bedrooms = models.IntegerField()
    bathrooms = models.DecimalField(max_digits=2, decimal_places=1)
    garage = models.IntegerField(default=0)
    homesize = models.IntegerField()
    landsize = models.DecimalField(max_digits=5, decimal_places=1)
    top_photo = models.FileField(upload_to='pictures/%Y/%m/%d/')
    picture1 = models.FileField(upload_to='pictures/%Y/%m/%d/', blank=True)
    picture2 = models.FileField(upload_to='pictures/%Y/%m/%d/', blank=True)
    picture3 = models.FileField(upload_to='pictures/%Y/%m/%d/', blank=True)
    picture4 = models.FileField(upload_to='pictures/%Y/%m/%d/', blank=True)
    picture5 = models.FileField(upload_to='pictures/%Y/%m/%d/', blank=True)
    picture6 = models.FileField(upload_to='pictures/%Y/%m/%d/', blank=True)
    is_posted = models.BooleanField(default=True)
    date_posted = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.property_title

class Appointments(models.Model):
    date = models.CharField(max_length=100)
    agent = models.ForeignKey(Agent, on_delete=models.CASCADE, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, related_name=None)
    home = models.ForeignKey(Home, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return str(self.user)

homes/forms.py
from django import forms
#from django.db import models

from .models import Appointments

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column


from .models import Home

class SellerForm(forms.ModelForm):


    class Meta:
        model = Home
        fields = ('property_title', 'address', 'city', 'state', 'zipcode', 'information', 'price', 
                  'bedrooms', 'bathrooms', 'garage', 'homesize', 'landsize', 'top_photo', 'picture1',
                  'picture2', 'picture3', 'picture4', 'picture5', 'picture6', 'is_posted', 'date_posted'
                )

    def clean_property_title(self, *args, **kwargs):
        property_title = self.cleaned_data.get('property_title')
        word_count = len(property_title)
        if word_count > 25:
            raise forms.ValidationError("This field is too long")
        if property_title == "":
            raise forms.ValidationError("Empty. Fill the field")
        
        return property_title

    def clean_address(self, *args, **kwargs):
        address = self.cleaned_data.get('address')
        word_count = len(address)
        if word_count > 25:
            raise forms.ValidationError("This field is too long")
        if not address:
            raise forms.ValidationError("Empty. Fill the field")
        
        return address

    def clean_zipcode(self, *args, **kwargs):
        zipcode = self.cleaned_data.get('zipcode')
        word_count = len(zipcode)
        if word_count != 5:
            raise forms.ValidationError("Five numeric strings are needed")
        if not zipcode:
            raise forms.ValidationError("Empty. Choose a State")
        if not zipcode.isdigit():
            raise forms.ValidationError('Phone number can only contains digits')
    
        return zipcode

    def clean_city(self, *args, **kwargs):
        city = self.cleaned_data.get('city')
        if len(city) > 25:
            raise forms.ValidationError("This field is too long")
        if not city:
            raise forms.ValidationError("Empty. Fill the field")
        
        return city
    
    def clean_price(self, *args, **kwargs):
        price = self.cleaned_data.get('price')
        word_count = len(str(price).split())
        if word_count > 9:
             raise forms.ValidationError("This field should contain a minimum of 9 integers")
        
        return price



    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.layout = Layout(
            'property_title',
            'address',
            Row(
                Column('city', css_class='form-group col-md-4 mb-0'),
                Column('state', css_class='form-group col-md-4 mb-0'),
                Column('zipcode', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
            'information',
            'price',
            Row(
                Column('bedrooms', css_class='form-group col-md-4 mb-0'),
                Column('bathrooms', css_class='form-group col-md-4 mb-0'),
                Column('garage', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('homesize', css_class='form-group col-md-4 mb-0'),
                Column('landsize', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('top_photo', css_class='form-group col-md-4 p-4'),
                Column('picture1', css_class='form-group col-md-4 p-4'),
                Column('picture2', css_class='form-group col-md-4 p-4'),
                css_class='form-row'
            ),
            Row(
                Column('picture3', css_class='form-group col-md-4 p-4'),
                Column('picture4', css_class='form-group col-md-4 p-4'),
                css_class='form-row'
            ),
            Row(
                Column('picture5', css_class='form-group col-md-4 p-4'),
                Column('picture6', css_class='form-group col-md-4 p-4'),
                css_class='form-row'
            ),
            'is_posted',
            'date_posted',
            
            Submit('submit', 'Post your house')
        )

    
class ScheduleTourForm(forms.ModelForm):
    class Meta:
        model = Appointments
        fields= '__all__'

homes/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .models import Home
from django.db.models import Q
from .forms import SellerForm, ScheduleTourForm

# Create your views here.

def homeList(request):

    homes = Home.objects.all()

    context = {
        'homes': homes
    }

    return render(request, 'home_listings/homes.html', context)
    
def home(request, home_id):

    home = get_object_or_404(Home, pk=home_id)

    if request.method == 'POST':
        form = ScheduleTourForm(request.POST)
        if form.is_valid():
            #data = (form.cleaned_data)
            form.save()
    
    else:
        form = ScheduleTourForm()
 
    context = {
        'home': home,
        'form': form
    }

    return render(request, 'home_listings/home.html', context)


def lookup(request):
    home_search = Home.objects.all()

    srch = request.GET.get("search")
    if srch:
        home_search = home_search.filter(
            Q(city__iexact=srch) |
            Q(state__iexact=srch) |
            Q(zipcode__iexact=srch) |
            Q(address__icontains=srch) |
            Q(address__icontains=srch) |
            Q(property_title__icontains=srch) |
            Q(bedrooms__iexact=srch) |
            Q(bathrooms__iexact=srch)

        )


    context = {
        'homes': home_search
    }

    return render(request, 'home_listings/lookup.html', context)



def seller(request): 
    if request.method == 'POST':
        form = SellerForm(request.POST, request.FILES)
        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.save()
            return redirect('homes')
    else:
        form = SellerForm()

    return render(request, 'sellers/seller_form.html', {
        'form': form
    })

templates/home_listings/home.html
{% extends 'base.html' %}
{% load humanize %}

{% block links %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">

  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

  <script>
      $(function(){
      $("#id_date").datepicker({
      showButtonPanel:true,});
      });

  </script>
<script type="text/javascript">
    $("#scheduleform").resetForm();
    </script>
  {% endblock %}

{% block content %}

<!-- Modal -->
<div class="modal fade" id="contactAgent" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle">Contact Agent for {{ home.address }}</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                    <form method="POST" action="{% url 'info' %}">
                            {% csrf_token %}
                            {% if user.is_authenticated %}
                               <input type="hidden" name="user_id" value="{{ user.id }}">
                            {% else %}
                            <input type="hidden" name="user_id" value="0">
                            {% endif %}
                            <input type="hidden" name="agent_email" value="{{ home.agent.email }}">
                            <input type="hidden" name="home_id" value="{{ home.id }}">
                                <div class="form-group">
                                <label for="name"></label>
                                <input type="text" class="form-control" name="name" {% if user.is_authenticated %} 
                                  value="{{ user.username }}" {% endif %} id="name" placeholder="Your Name">
                              </div>
                              <div class="form-group">
                                  <label for="phone"></label>
                                  <input type="text" class="form-control" name="phone" placeholder="Phone">
                             </div>
                                <div class="form-group">
                                  <label for="email1"></label>
                                  <input type="email" class="form-control" name="email" {% if user.is_authenticated %} 
                                  value="{{ user.email }}" {% endif %} id="email1" aria-describedby="emailHelp" placeholder="Enter email">
                                  
                                </div>
                                <div class="form-group">
                                    <label for="info"></label>
                                    <textarea class="form-control" name="info" rows="3" placeholder="I am interested in {{ home.property_title }}"></textarea>
                                </div>
                                <button type="submit" class="btn btn-primary">Submit</button>
                              </form>
                    
            </div>
            
          </div>
</div>
</div>
<div class="modal fade" id="scheduledtour" tabindex="-1" role="dialog" aria-labelledby="schedule" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="schedule">Schedule a tour</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                        <form action="" method="post" id="scheduleform">
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    <input type="submit" value="Submit" class="btn btn-primary">
                        </form>

            </div>

          </div>
</div>
</div>
<section id="homeBkground" class="pt-5">
    <div class="container pt-5">
        <div class="row">
            <div class="col-sm-6">
                <div class="card" id="cardCenter" style="width: 30rem;">
                        <h5 class="card-header">{{ home.property_title }} &nbsp; <span>Agent: {{ home.agent.name }}</span></h5>
                        <div class="card-header">
                                <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#contactAgent">Contact Agent</button>
                                <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#scheduledtour">Schedule a tour</button>
                        </div>
                        <div class="card-body">
                            <h4 class="card-title">${{ home.price | intcomma }}</h4>
                            <h5 class="card-title">{{ home.address }}</h5>
                            <p>{{ home.city }}, {{ home.state }} {{ home.zipcode }}</p>
                            <hr>
                                <div class="row py-2 text-secondary">
                                    <div class="col-6">{{ home.homesize  | intcomma }} sqft</div>
                        
                                    <div class="col-6">Garage: {{ home.garage }}</div>
                                </div>
                                <div class="row py-2 text-secondary">
                                    <div class="col-6">Bds: {{ home.bedrooms }}</div>
                                    <div class="col-6">Ba: {{ home.bathrooms }}</div>
                                </div>
                            <hr>
                        </div>
                        {% include 'dividers/_message.html' %}
                        
                </div>
            </div>
            <div class="picList col-md-4">
                <div class="row">
                    <div class="col-md-5 mb-2">
                        <div class="card">
                            <a href="{{ home.top_photo.url }}" data-lightbox="pixPics"><img src="{{ home.top_photo.url }}" class="card-img-top" alt=""></a>
                        </div>
                    </div>
                    {% if home.picture1 %}
                    <div class="col-md-5">
                        <div class="card">
                            <a href="{{ home.picture1.url }}" data-lightbox="pixPics"><img src="{{ home.picture1.url }}" class="card-img-top" alt=""></a>
                        </div>
                    </div>
                    {% endif %}
                    {% if home.picture2 %}
                    <div class="col-md-5">
                            <div class="card">
                                <a href="{{ home.picture2.url }}" data-lightbox="pixPics"><img src="{{ home.picture2.url }}" class="card-img-top" alt=""></a>
                            </div>
                    </div>
                    {% endif %}
                    {% if home.picture3 %}
                    <div class="col-md-5 mb-2">
                            <div class="card">
                                <a href="{{ home.picture3.url }}" data-lightbox="pixPics"><img src="{{ home.picture3.url }}" class="card-img-top" alt=""></a>
                            </div>
                    </div>
                    {% endif %}
                    {% if home.picture4 %}
                    <div class="col-md-5 mb-2">
                            <div class="card">
                                <a href="{{ home.picture4.url }}" data-lightbox="pixPics"><img src="{{ home.picture4.url }}" class="card-img-top" alt=""></a>
                            </div>
                    </div>
                    {% endif %}
                    {% if home.picture5 %}
                    <div class="col-md-5 mb-2">
                            <div class="card">
                                <a href="{{ home.picture5.url }}" data-lightbox="pixPics"><img src="{{ home.picture5.url }}" class="card-img-top" alt=""></a>
                            </div>
                    </div>
                    {% endif %}
                    {% if home.picture6 %}
                    <div class="col-md-5">
                            <div class="card">
                                <a href="{{ home.picture6.url }}" data-lightbox="pixPics"><img src="{{ home.picture6.url }}" class="card-img-top" alt=""></a>
                            </div>
                    </div>
                    {% endif %}
                </div>
                

            </div>
        </div>
    </div>
</section>

    
{% endblock %}


 

templates/home_listings/homes.html
{% extends 'base.html' %}
{% load humanize %}


{% block content %}


      
        
   
 <section id="homes" class="pt-5">
        <div class="container pt-5">
            <div class="row">
                {% if homes  %}
                    {% for home in homes %}
                    
                    <div class="col-md-3 mb-4">
                      <div class="card openBtn">
                          <a href="{% url 'home' home.id %}">
                             <img src="{{ home.top_photo.url }}" class="card-img-top" alt="...">
                             <div class="card-img-overlay">
                               <p class="card-title">{{ home.date_posted | timesince }}</p>
                             </div>
                          </a>
                        <div class="card-body">
                          <h4 class="card-title">${{ home.price | intcomma }}</h4>
                          <h5 class="card-title">{{ home.address }}</h5>
                          <p>{{ home.city }}, {{ home.state }} {{ home.zipcode }}</p>
                          <hr>
                            <div class="row py-2 text-secondary">
                                <div class="col-6">{{ home.homesize  | intcomma }} sqft</div>
                      
                                <div class="col-6"></i> Garage: {{ home.garage }}</div>
                            </div>
                            <div class="row py-2 text-secondary">
                                <div class="col-6">Bds: {{ home.bedrooms }}</div>
                                <div class="col-6">Ba: {{ home.bathrooms }}</div>
                            </div>
                          <hr>
                        </div>
                      </div>
                    </div>
                  

                {% endfor %}

                {% else %}
                  <div class="col-md-10">
                      <p>No Homes listed</p>
                  </div>

                {% endif %}
            </div>    
                
            
        </div>
        
            
 </section>
    
{% endblock %}


 

templates/home_listings/lookup.html
{% extends 'base.html' %}
{% load humanize %}


{% block content %}
 <section id="homes" class="pt-5">
        <div class="container pt-5">
            <div class="card-deck">
                {% if homes  %}
                    {% for home in homes %}
                    <div class="card">
                        <img src="{{ home.top_photo.url }}" class="card-img-top" alt="...">
                        <div class="card-body">
                          <h4 class="card-title">${{ home.price | intcomma }}</h4class></h4>
                          <h5 class="card-title">{{ home.address }}</h5>
                          <p>{{ home.city }}, {{ home.state }} {{ home.zipcode }}</p>
                          <hr>
                            <div class="row py-2 text-secondary">
                                <div class="col-6">{{ home.homesize  | intcomma }} sqft</div>
                      
                                <div class="col-6">Garage: {{ home.garage }}</div>
                            </div>
                            <div class="row py-2 text-secondary">
                                <div class="col-6">Bds: {{ home.bedrooms }}</div>
                                <div class="col-6">Ba: {{ home.bathrooms }}</div>
                            </div>
                        <hr>
                        </div>
                      </div>
                  

                {% endfor %}

                {% else %}
                  <div class="col-md-12">
                      <p>No Homes listed</p>
                  </div>

                {% endif %}
            </div>    
                
            
        </div>
 </section>
    
{% endblock %}


 